# snippets_dgstack_notshared is used to load a full Panorama configuration
# this is a complete Panorama and reference device-group and template stack configuration
# all values are contained in the device-groups and template stacks; nothing shared

# snippet folder name
name: skillet_panorama_dgstack_notshared_v90
# label used for menu selection
label: v9.0 Iron-Skillet for Panorama with Device-Group and Stack only (No Shared Values)
description: Iron Skillet device-group and template stack config for Panorama
dependency: snippets
# type of device configuration
type: panorama
extends:

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  service_type: iron_skillet
  collection:
    - IronSkillet
    - Configure
    - Best Practice

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: STACK
    description: Template stack name for Panorama
    default: sample_stack
    type_hint: text   
  - name: DEVICE_GROUP
    description: Device-group name for Panorama
    default: sample_devicegroup
    type_hint: text     
  - name: FW_NAME
    description: Device Name for NGFW
    default: sample
    type_hint: text
  - name: MGMT_TYPE
    description: firewall management IP type
    default: dhcp-client
    type_hint: dropdown
    dd_list:
      - key: dhcp-client
        value: dhcp-client
      - key: static
        value: static
  - name: MGMT_IP
    description: NGFW management IP
    default: 192.0.2.6
    type_hint: ip_address
  - name: MGMT_MASK
    description: NGFW management netmask
    type_hint: ip_address
    default: 255.255.255.0
  - name: MGMT_DG
    description: NGFW management default gateway
    default: 192.0.2.7
    type_hint: ip_address
  - name: NTP_1
    description: Network Time Protocol Server
    default: 0.pool.ntp.org
    type_hint: text
  - name: NTP_2
    description: Network Time Protocol Server 2
    default: 1.pool.ntp.org
    type_hint: text
  - name: ADMINISTRATOR_USERNAME
    description: admin username
    default: admin
    type_hint: text
  - name: ADMINISTRATOR_PASSWORD
    description: admin password
    default: admin
    type_hint: password
  - name: DNS_1
    description: primary dns server
    default: 8.8.8.8
    type_hint: ip_address
  - name: DNS_2
    description: secondary dns server
    default: 8.8.4.4
    type_hint: ip_address
  - name: SINKHOLE_IPV4
    description: sinkhole FQDN IPv4
    default: sinkhole.paloaltonetworks.com
    type_hint: text
  - name: SINKHOLE_IPV6
    description: sinkhole address IPv6
    default: 2600:5200::1
    type_hint: ip_address
  - name: EMAIL_PROFILE_GATEWAY
    description: email gateway address for critical alerts
    default: 192.0.2.1
    type_hint: text
  - name: EMAIL_PROFILE_FROM
    description: from address in email alerts
    default: sentfrom@yourdomain.com
    type_hint: text
  - name: EMAIL_PROFILE_TO
    description: to address in email alerts
    default: sendto@yourdomain.com
    type_hint: text
  - name: SYSLOG_SERVER
    description: syslog server ip address
    default: 192.0.2.2
    type_hint: text
  - name: API_KEY_LIFETIME
    description: lifetime for the api key in minutes
    default: 525600
    type_hint: text
# option built into the templates to ignore the panw published external dynamic lists security rules
# should ONLY be excluded based on licensing limitations outside of best practices
# when 'yes' (default) will include the EDL rule
  - name: INCLUDE_PAN_EDL
    description: include the predefined Palo Alto Networks external lists security rules
    default: 'no'
    type_hint: dropdown
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: template
    xpath: /config/devices/entry[@name='localhost.localdomain']/template
    file: ../snippets/template.xml
  - name: stack
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack
    file: ../snippets/template_stack.xml
# adding in the email profile so scheduler loads
  - name: panorama_log_settings
    xpath: /config/panorama/log-settings
    file: panorama_log_settings.xml
  - name: device_system_ip_hostname
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ STACK }}']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: ../snippets/device_system_local.xml
  - name: device_system_services
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ STACK }}']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: ../snippets/device_system_shared.xml
  - name: device_setting
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ STACK }}']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting
    file: ../snippets/device_setting.xml
  - name: device_mgt_config
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ STACK }}']/config/mgt-config
    file: ../snippets/device_mgt_config.xml
  - name: shared_log_settings
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ STACK }}']/config/shared/log-settings
    file: ../snippets/shared_log_settings.xml
  - name: zone_protection_profile
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ STACK }}']/config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile
    file: ../snippets/zone_protection_profile.xml
  - name: devicegroup
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group
    file: ../snippets/device_group.xml
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/tag
    file: ../snippets/tag.xml
  - name: address
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/address
    file: ../snippets/address.xml
  - name: local_log_profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/log-settings/profiles
    file: ../snippets/log_settings_profiles.xml
  - name: profiles_custom_url_category
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/profiles/custom-url-category
    file: ../snippets/profiles_custom_url_category.xml
  - name: profiles_decryption
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/profiles/decryption
    file: ../snippets/profiles_decryption.xml
  - name: profiles_virus
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/profiles/virus
    file: ../snippets/profiles_virus.xml
  - name: profiles_spyware
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/profiles/spyware
    file: ../snippets/profiles_spyware.xml
  - name: profiles_vulnerability
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/profiles/vulnerability
    file: ../snippets/profiles_vulnerability.xml
  - name: profiles_file_blocking
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/profiles/file-blocking
    file: ../snippets/profiles_file_blocking.xml
  - name: profiles_url_filtering
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/profiles/url-filtering
    file: ../snippets/profiles_url_filtering.xml
  - name: profiles_wildfire_analysis
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/profiles/wildfire-analysis
    file: ../snippets/profiles_wildfire_analysis.xml
  - name: profile_group
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/profile-group
    file: ../snippets/profile_group.xml
  - name: post_rulebase_default_security_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/post-rulebase/default-security-rules
    file: ../snippets/post_rulebase_default_security_rules.xml
  - name: pre_rulebase_security
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/pre-rulebase/security
    file: ../snippets/pre_rulebase_security.xml
  - name: post_rulebase_decryption
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/post-rulebase/decryption
    file: ../snippets/post_rulebase_decryption.xml
  - name: pre_rulebase_decryption
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/pre-rulebase/decryption
    file: ../snippets/pre_rulebase_decryption.xml
  - name: reports
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/reports
    file: ../snippets/reports_simple.xml
  - name: report_group_simple
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/report-group
    file: ../snippets/report_group_simple.xml
  - name: email_scheduler_simple
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/email-scheduler
    file: ../snippets/email_scheduler_simple.xml