name: vm50_deletes_rest
label: Delete profile objects for VM50 reduction

description: |
  Quick delete of recommended profile objects if IronSkillet loaded on VM50

type: rest

extends:

labels:
  collection:
    - Configure
    - PANOS
    - IronSkillet

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: ip_address
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password


snippets:
# get API key used in additional API calls
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key
# delete Internet profile group and associated profiles
  - name: delete_internal_profile_group
    path: >-
      https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/profile-group/entry[@name='Internal']&key={{ api_key }}
  - name: delete_internal_profile_virus
    path: >-
      https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/profiles/virus/entry[@name='Internal-AV']&key={{ api_key }}
  - name: delete_internal_profile_spyware
    path: >-
      https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/profiles/spyware/entry[@name='Internal-AS']&key={{ api_key }}
  - name: delete_internal_profile_vulnerability
    path: >-
      https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/profiles/vulnerability/entry[@name='Internal-VP']&key={{ api_key }}
  - name: delete_internal_profile_file_blocking
    path: >-
      https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/profiles/file-blocking/entry[@name='Internal-FB']&key={{ api_key }}
  - name: delete_internal_profile_wildfire
    path: >-
      https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/profiles/wildfire-analysis/entry[@name='Internal-WF']&key={{ api_key }}
# delete Exception profiles
  - name: delete_exception_virus
    path: >-
      https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/profiles/virus/entry[@name='Exception-AV']&key={{ api_key }}
  - name: delete_exception_spyware
    path: >-
      https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/profiles/spyware/entry[@name='Exception-AS']&key={{ api_key }}
  - name: delete_exception_vulnerability
    path: >-
      https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/profiles/vulnerability/entry[@name='Exception-VP']&key={{ api_key }}
  - name: delete_exception_url
    path: >-
      https://{{ TARGET_IP }}/api/?type=config&action=delete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/profiles/url-filtering/entry[@name='Exception-URL']&key={{ api_key }}